---
engines:
  csslint:
    enabled: true
    config:
      config: test/fixtures/config/.csslintrc
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    config:
      config: test/fixtures/config/.eslintrc
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.css"
exclude_paths:
- test/
- assets/
- parts/
- index.js
- gulpfile.js
